addons:
  apt:
    packages:
      - sshpass

services:
  - docker

sudo: required

language: generic

if: branch = master

before_install:

  - export SSHPASS=$DEPLOY_PASS
  - export SSH_CMD="sshpass -e ssh -p $DEPLOY_PORT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

install:
  - docker-compose -f docker-compose.yml build

after_success:
  - docker save web-test | $SSH_CMD $DEPLOY_USER@$DEPLOY_HOST docker load
  - rsync -e "$SSH_CMD" docker-compose.yml $DEPLOY_USER@$DEPLOY_HOST:~/web/
  - $SSH_CMD $DEPLOY_USER@$DEPLOY_HOST "cd web && docker-compose down && docker-compose up -d"
